services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  python:
    image: python:latest
    container_name: python
    restart: unless-stopped
    ports:
      - 8080:8080
    command: python -m http.server 8080